query GetSneaker($productId: String) {
  sneaker(where: {slug: $productId}) {
    id
    name
    description
    price
    quantity
    slug
    brand {
      id
      name
    }
    category {
      slug
      name
    }
    coverImg {
      url
    }
    images {
      url
    }
    ratings {
      stars
    }
  }
}